project:
  type: website

website:
  title: Simplicial
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: light
    right: 
      - icon: github
        href: https://github.com
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Overview 
        href: overview.qmd
      - text: Design 
        href: design.qmd
      - text: Simplex Tree
        href: simplextree_ds.qmd
      - text: Test
        href: test.qmd
      - section: API
        contents: 
          - meta.rst
          - simplicial_ds.rst
          - simplextree.rst
  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2023, Matthew Piekenbrock" 
    border: true

format:
  html: 
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    fontsize: 18px
    linestretch: 1.2
    margin-top: "0px" 
    css: styles.css

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly
  