[build-system]
requires = ["setuptools>=42", "wheel", "numpy", "pybind11"] # "setuptools", pybind11, "scikit-build>=0.13", "cmake", "ninja"
build-backend = "setuptools.build_meta"
# build-backend = "hatchling.build"

# Validate with: validate-pyproject pyproject.toml 
[project]
name = "simplicial"
authors = [
	{ name = "Matt Piekenbrock", email = "matt.piekenbrock@gmail.com" }
]
version = "0.1.0"
# readme = "README.md"
description = "a"
license = { file = "LICENSE.txt" }
requires-python = ">=3.8"
keywords = ["TDA"]