[build-system]
requires = ["setuptools>=42", "wheel", "numpy", "pybind11"] 
build-backend = "setuptools.build_meta"

# Validate with: validate-pyproject pyproject.toml 
[project]
name = "splex"
authors = [
	{ name = "Matt Piekenbrock", email = "matt.piekenbrock@gmail.com" }
]
version = "0.2.0"
# readme = "README.md"
description = "a"
license = { file = "LICENSE" }
requires-python = ">=3.8"
keywords = ["TDA"]