## Build the docs by cd'ing into docs and doing: 
## quarto render .
## python -m quartodoc build
## python gen_api_custom.py
project:
  type: website
  output-dir: ../docs

website:
  title: Splex
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: light
    right: 
      - icon: github
        href: https://github.com
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Overview 
        href: pages/overview.qmd
      # - text: Vignettes 
      # - text: Package design 
      #   href: pages/design.qmd
      - section: API Reference
        href: reference/index.qmd
        contents:
          - section: Complexes
            contents: 
              - name: complexes.SetComplex.SetComplex
                text: Set Complex
                href: reference/complexes.SetComplex.SetComplex.qmd
              - name: complexes.RankComplex.RankComplex
                text: Rank Complex
                href: reference/complexes.RankComplex.RankComplex.qmd
              - name: complexes.SimplexTree.SimplexTree
                text: Simplex Tree
                href: reference/complexes.SimplexTree.SimplexTree.qmd
          - section: Filtrations
            contents: 
              - name: filtrations.SetFiltration.SetFiltration 
                text: Set Filtration 
                href: reference/filtrations.SetFiltration.SetFiltration.qmd
          - section: Generics 
            contents: 
              - name: generics.card
                text: Cardinality  
                href: reference/generics.card.qmd
              - name: generics.dim
                text: Dimension 
                href: reference/generics.dim.qmd
              - name: generics.faces
                text: Faces   
                href: reference/generics.faces.qmd
          - section: Interface 
            contents: 
              - name: meta 
                text: Protocol Classes
                href: reference/meta.qmd
          - section: Linear Algebra 
            contents: 
              - name: sparse
                text: Sparse 
                href: reference/sparse.qmd
          - name: UnionFind 
            text: Union Find
            href: reference/UnionFind.UnionFind.qmd
      #   href: reference/index.qmd
      # - section: API Reference
      #   contents: 
      #     - text: SimplexTree
      #       href: reference/SimplexTree.qmd
      #     - text: SetComplex
      #       href: reference/SetComplex.qmd
      #     - text: RankComplex
      #       href: reference/RankComplex.qmd

  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2023, Matthew Piekenbrock" 
    border: true

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly

format:
  html: 
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    fontsize: 14px
    linestretch: 1.3
    margin-top: "0px" 
    css: static/styles.css

quartodoc: 
  package: splex
  title: API Reference    # API only 
  dir: reference          # API only 
  style: pkgdown          # API only
  # sidebar: _sidebar.yml 
  renderer: 
    style: _renderer.py
    show_signature: true
    show_signature_annotations: true
    display_name: name 
  sections:
    - title: Complexes 
      desc: Data structures for constructing and modifying abstract simplicial complexes 
      contents: 
        - complexes.SetComplex.SetComplex
        - complexes.RankComplex.RankComplex
        - complexes.SimplexTree.SimplexTree
    - title: Filtrations  
      desc: Data structures for constructing and modifying filtered simplicial complexes
      contents: 
        - filtrations.SetFiltration.SetFiltration
    - title: Generics
      desc: Generic functions that work with any simplicial representation that supports the Protocol interface. 
      contents:
        - name: generics
          children: flat
    - title: Protocols 
      desc: Protocol classes that define loose interfaces for duck typing and structural subtyping support. 
      contents:
        - name: meta
          children: flat
    - title: Protocols 
      desc: Protocol classes that define loose interfaces for duck typing and structural subtyping support. 
      contents:
        - name: meta
          children: flat
    - title: Geometry
      desc: Functions for constructing simplicial complexes and filtrations from geometric settings. 
      contents: 
        - name: geometry 
          children: embedded
    - title: Linear algebra
      desc: Functions useful for performing linear algebraic operations on simplicial complexes. 
      contents: 
        - name: sparse 
          children: embedded


# out_index: pages/index.qmd
# sphinx-build . ./_build/html -b html