# API Reference

## Complexes

Data structures for constructing and modifying abstract simplicial complexes

| | |
| --- | --- |
| [complexes.SetComplex.SetComplex](complexes.SetComplex.SetComplex.qmd#splex.complexes.SetComplex.SetComplex) | Abstract Simplicial Complex |
| [complexes.RankComplex.RankComplex](complexes.RankComplex.RankComplex.qmd#splex.complexes.RankComplex.RankComplex) | Simplicial complex represented via the combinatorial number system. |
| [complexes.SimplexTree.SimplexTree](complexes.SimplexTree.SimplexTree.qmd#splex.complexes.SimplexTree.SimplexTree) | SimplexTree provides lightweight wrapper around a Simplex Tree data structure: an ordered, trie-like structure whose nodes are in bijection with the faces of the complex.  |

## Filtrations

Data structures for constructing and modifying filtered simplicial complexes

| | |
| --- | --- |
| [filtrations.SetFiltration.SetFiltration](filtrations.SetFiltration.SetFiltration.qmd#splex.filtrations.SetFiltration.SetFiltration) | Filtered complex of simplices uses _SortedSet_. |

## Generics

Generic functions that work with any simplicial representation that supports the Protocol interface.

| | |
| --- | --- |
| [generics](generics.qmd#splex.generics) |  |

## Protocols

Protocol classes that define loose interfaces for duck typing and structural subtyping support.

| | |
| --- | --- |
| [meta](meta.qmd#splex.meta) |  |

## Protocols

Protocol classes that define loose interfaces for duck typing and structural subtyping support.

| | |
| --- | --- |
| [meta](meta.qmd#splex.meta) |  |

## Geometry

Functions for constructing simplicial complexes and filtrations from geometric settings.

| | |
| --- | --- |
| [geometry](geometry.qmd#splex.geometry) |  |

## Linear algebra

Functions useful for performing linear algebraic operations on simplicial complexes.

| | |
| --- | --- |
| [sparse](sparse.qmd#splex.sparse) |  |