# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Simplicial
author: Matt Piekenbrock

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/peekxc/simplicial  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

# jb config sphinx docs && sphinx-build docs docs/_build/html -b html
sphinx:
  extra_extensions:
   - 'sphinx.ext.autodoc'
   - 'sphinx.ext.napoleon'
   - 'sphinx.ext.viewcode'
   - 'sphinx.ext.autosummary'
   - 'sphinx_autodoc_typehints'
  #  - 'sphinx_inline_tabs'
   - 'sphinxcontrib.katex'
  config:
    katex_prerender: True
    add_module_names: True
    autosummary_generate: True
    napoleon_preprocess_types: True 
    napoleon_use_param: True # keep to true 
    napoleon_use_ivar: False
    napoleon_use_rtype: True ## keep to true 
    napoleon_attr_annotations: False
    napoleon_type_aliases: {
      'array-like': ':term:`array-like <array_like>`',
      'array_like': ':term:`array_like`',
      'ArrayLike': ':term:`ArrayLike`',
      'ArrayLike': "ArrayLike"
    }
    napoleon_custom_sections: ["Properties", "Fields"]
    autodoc_type_aliases: {
      'ArrayLike': 'ArrayLike'
    }
    autodoc_typehints_format: 'short'
    typehints_use_signature: False # https://pypi.org/project/sphinx-autodoc-typehints/
    simplify_optional_unions: True
    python_use_unqualified_type_names: True # If true, suppress the module name of the python reference if it can be resolved.
    always_document_param_types: False

# sphinx-build docs docs/_build/html -b html
###############################################################################
# import os 
# import sys 
# print("Python Executable: " + sys.executable)
# sys.path.insert(0, os.path.abspath('..'))
# sys.path.append('/Users/mpiekenbrock/simplicial')
# sys.path.append(os.path.join(os.path.dirname(__name__), '..'))