## Build the docs by cd'ing into docs and doing: 
## quarto render .
## python -m quartodoc build
## python gen_api_custom.py
project:
  type: website
  output-dir: _site

# sphinx-build . ./_build/html -b html

website:
  title: Splex
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: light
    right: 
      - icon: github
        href: https://github.com
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Overview 
        href: overview.qmd
      # - text: Design 
      #   href: design.qmd
      # - text: Simplex Tree
      #   href: simplextree_ds.qmd
      # - text: API Overview
      #   href: reference/index.qmd
      - section: API Reference
        contents: 
          - text: SimplexTree
            href: reference/SimplexTree.qmd
          - text: SetComplex
            href: reference/SetComplex.qmd
          - text: RankComplex
            href: reference/RankComplex.md

  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2023, Matthew Piekenbrock" 
    border: true

format:
  html: 
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    fontsize: 18px
    linestretch: 1.2
    margin-top: "0px" 
    css: styles.css

# metadata-files:
#   - _sidebar.yml

quartodoc: 
  title: API Reference
  package: splex
  dir: reference
  renderer: 
    style: markdown
    show_signature: true
    show_signature_annotations: true
    display_name: name 
  # sidebar: "_sidebar.yml"
  style: pkgdown
  sections:
    - title: Explicit classes 
      desc: Classes which represent simplicial complexes explicitly
      contents:
        - MutableFiltration
        - SimplicialComplex
        - SimplexTree
    - title: Protocols 
      desc: Structural subtypes for various types of simplicial complexes. 
      contents: 
        - SimplexLike 
        - ComplexLike 
        - FiltrationLike
        

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly
  