## Build the docs by cd'ing into docs and doing: 
## quarto render .
## python -m quartodoc build
## python gen_api_custom.py
project:
  type: website
  output-dir: _site

website:
  title: Splex
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: light
    right: 
      - icon: github
        href: https://github.com
    pinned: false  
    search: false       
  sidebar:
    style: "docked"
    pinned: false
    align: center 
    search: true
    border: true 
    collapse-level: 2
    contents: 
      - text: Overview 
        href: pages/overview.qmd
      - section: API Reference
        href: reference/index.qmd
        contents:
          - text: Faces
            href: reference/faces.qmd
      # - text: Design 
      #   href: design.qmd
      # - text: Simplex Tree
      #   href: simplextree_ds.qmd
      # - text: API Overview
      #   href: reference/index.qmd
      # - section: API Reference
      #   contents: 
      #     - text: SimplexTree
      #       href: reference/SimplexTree.qmd
      #     - text: SetComplex
      #       href: reference/SetComplex.qmd
      #     - text: RankComplex
      #       href: reference/RankComplex.qmd

  page-navigation: true
  reader-mode: true
  page-footer: 
    center: "Copyright 2023, Matthew Piekenbrock" 
    border: true

latex-auto-install: true 

execute:
  cache: true

theme: 
  light: flatly
  dark: darkly

format:
  html: 
    anchor-selections: true 
    code-fold: false
    smooth-scroll: true
    html-math-method: katex
    code-overflow: wrap 
    highlight-style: printing 
    fontsize: 14px
    linestretch: 1.1
    margin-top: "0px" 
    css: static/styles.css

# metadata-files:
#   - _sidebar.yml

quartodoc: 
  package: splex
  title: API Reference    # API only 
  dir: reference          # API only 
  style: pkgdown          # API only
  sidebar: None 
  # renderer: 
  #   # style: _renderer.py
  #   show_signature: true
  #   show_signature_annotations: true
  #   display_name: name 
  sections:
    - title: Simplex Tree 
      desc: Simplex Tree data structure 
      contents: 
        - complexes.SimplexTree
    - title: Generics
      desc: Generic functions
      contents:
        - generics.faces
        - generics.dim
        - generics.card
        - generics.boundary
    # - title: UnionFind
    #   desc: UnionFind data structure 
    #   contents: 
    #     - UnionFind.UnionFind


# out_index: pages/index.qmd
# sphinx-build . ./_build/html -b html