# SetComplex

 --- 

## SetComplex.SetComplex { #SetComplex.SetComplex }

`SetComplex.SetComplex(self, simplices: Iterable[SimplexConvertible] = None)`

Abstract Simplicial Complex

 --- 

## SetComplex.dim { #SetComplex.dim }

`SetComplex.dim(self)`

 --- 

## SetComplex.faces { #SetComplex.faces }

`SetComplex.faces(self, p: Optional[int] = None)`

 --- 

## SetComplex.card { #SetComplex.card }

`SetComplex.card(self, p: int = None)`

 --- 

## SetComplex.update { #SetComplex.update }

`SetComplex.update(self, simplices: Iterable[SimplexLike])`

 --- 

## SetComplex.add { #SetComplex.add }

`SetComplex.add(self, item: Collection[int])`

 --- 

## SetComplex.remove { #SetComplex.remove }

`SetComplex.remove(self, item: Collection[int])`

 --- 

## SetComplex.discard { #SetComplex.discard }

`SetComplex.discard(self, item: Collection[int])`

 --- 

## SetComplex.cofaces { #SetComplex.cofaces }

`SetComplex.cofaces(self, item: Collection[int])`

 --- 

## SetComplex.print { #SetComplex.print }

`SetComplex.print(self, kwargs)`