# SimplicialComplex

 --- 

## splex.SimplicialComplex { #splex.SimplicialComplex }

`splex.SimplicialComplex(self, simplices: Iterable[SimplexLike] = None)`

Abstract Simplicial Complex

 --- 

## SimplicialComplex.dim { #SimplicialComplex.dim }

`SimplicialComplex.dim(self)`

 --- 

## SimplicialComplex.faces { #SimplicialComplex.faces }

`SimplicialComplex.faces(self, p: Optional[int] = None)`

 --- 

## SimplicialComplex.update { #SimplicialComplex.update }

`SimplicialComplex.update(self, simplices: Iterable[SimplexLike])`

 --- 

## SimplicialComplex.add { #SimplicialComplex.add }

`SimplicialComplex.add(self, item: Collection[int])`

 --- 

## SimplicialComplex.remove { #SimplicialComplex.remove }

`SimplicialComplex.remove(self, item: Collection[int])`

 --- 

## SimplicialComplex.discard { #SimplicialComplex.discard }

`SimplicialComplex.discard(self, item: Collection[int])`

 --- 

## SimplicialComplex.cofaces { #SimplicialComplex.cofaces }

`SimplicialComplex.cofaces(self, item: Collection[int])`

 --- 

## SimplicialComplex.print { #SimplicialComplex.print }

`SimplicialComplex.print(self, kwargs)`