name: Build windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_windows:      
    name: Windows - ${{ matrix.python-version }}
    runs-on: windows-latest
    env:
      COVERAGE_TOTAL: 60
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov coverage-badge coveralls pytest-benchmark
        pip install --verbose --editable .

    - name: pytester-cov
      id: pytester-cov
      uses: programmingwithalex/pytester-cov@main
      with:
        pytest-root-dir: '.'
        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}

    - name: Coverage total fail - exit
      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
      run: |
        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
        exit 1

  
    # - name: Test with pytest
    #   run: |
    #     python -m pytest tests/ --cov=splex --benchmark-skip
    #     coverage run --source=./src -m pytest tests/ --benchmark-skip
    #     coverage json -o tests/test_results.json
    #     coverage report -m

  # update_coverage:
  #   - if: matrix.os == 'windows-latest'  
  #     name: Create coverage badge
  #     uses: schneegans/dynamic-badges-action@v1.6.0
  #     with:
  #       auth: ${{ secrets.GIST_SECRET }}
  #       gistID: ef42349965f40edf4232737026690c5f
  #       filename: windows_info.json
  #       label: build
  #       message: ${{ env.COV_PERCENT }}
  #       valColorRange: ${{ env.COV_PERCENT }}
  #       maxColorRange: 100
  #       minColorRange: 0
  #       namedLogo: Pytest
