name: Build linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:      
    name: Ubuntu - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CC: g++
      CXX: g++
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: set flags 
      run: |
        echo "CC=g++" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov coverage-badge coveralls pytest-benchmark
        pip install --verbose --editable .
    - name: Test with pytest
      run: |
        python -m pytest tests/ --cov=splex --benchmark-skip
    - name: Run coverage
      run: |
        coverage json -o tests/test_results.json
        coverage report
    - if: matrix.os == 'ubuntu-latest'
      run: |
        COV_RESULT=$(cat tests/test_results.json)
        COV_PERCENT=$(echo $COV_RESULT | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["totals"]["percent_covered_display"])')
        echo "COV_PERCENT=$COV_PERCENT" >> $GITHUB_ENV
    - if: matrix.os == 'ubuntu-latest'  
      name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ef42349965f40edf4232737026690c5f
        filename: coverage_info.json
        label: coverage
        message: ${{ env.COV_PERCENT }}%
        valColorRange: ${{ env.COV_PERCENT }}
        maxColorRange: 100
        minColorRange: 0
        namedLogo: Pytest
    - name: Send coverage report
      run: |
        coveralls --service=github
