name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
      CC: g++
      CXX: g++
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_FLAG_NAME: Linux
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        pip install --verbose .
    - name: Test with pytest
      run: |
        python -m pytest tests/ --cov=src/ --cov-report lcov:tests/lcov.info
    # - name: Upload Coverage Results w/ coveralls-python 
    #   run: |
    #     coveralls
  coveralls:
    name: Indicate completion to coveralls.io
    needs: build_linux
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Upload Coverage Results w/ Coveralls.io app
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.github_token }}
    #     path-to-lcov: tests/lcov.info
        
  build_windows: # Since github cannot figure out how to make a clean API, repeat the same
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install --verbose .
    - name: Test with pytest
      run: |
        python -m pytest tests/
        
  build_osx: # Since github cannot figure out how to make a clean API, repeat the same
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install --verbose .
    - name: Test with pytest
      run: |
        python -m pytest tests/
    # - name: Coveralls GitHub Action
    #   uses: coverallsapp/github-action@1.1.3

  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #     - name: Install cibuildwheel
  #       run: python -m pip install cibuildwheel==2.12.0
  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl