name: Package Wheels and upload to PyPI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]
  release:
    types: ["published"]

jobs:
  build_sdist:
    name: Build package source distribution (SDist)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true 
    
    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: "3.9"

    - name: Build SDist
      run: python -m build --sdist -o dist/

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.os_python }} ${{ matrix.os_arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        os_python: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
        os_arch: ["x86_64"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.9"

      - name: Build the wheel
        # run: python -m pip wheel -w dist .
        run: python -m build --wheel -o dist/ --no-isolation
          
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl

  upload_all:
    needs: [build_sdist, build_wheels]
    # if: startsWith(github.ref, 'refs/tags/v') # this doesn't work
    environment: 
      name: pypi
      url: https://pypi.org/p/combin
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: false # https://github.com/pypa/gh-action-pypi-publish/issues/200
        verbose: true